_target_: src.models.lstm_module.LSTMModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_bilstm_net.SimpleBiLstmNet
  vocab_size: 784
  embedding_dim: 300
  hidden_dim: 128
  num_layers: 2
  bidirectional: True
  dropout: 0.1
